services:
  mysql-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - mysql-volumes:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-volumes:
    driver: local

networks:
  mysql-network:
    driver: bridge
